# Generated by Django 3.2.15 on 2022-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
