# Generated by Django 3.2.15 on 2022-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220823_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('collection', models.ManyToManyField(to='movie.Collection')),
            ],
        ),
    ]
